name: Test CI-CD pipeline

on: 
    push: 
        branches: [master]

jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
            - run:
                echo "Install Python"
                Install Python 3.11
                

            
   
  
